version: '3'
networks:
  wabot_network:
    driver: bridge
services:

  engine:
    networks:
      - wabot_network
    build:
      context: ./
      dockerfile: docker/engine.dockerfile
    image: wabot_engine
    container_name: wabot_engine
    ports:
        - "3002:3002"
    volumes:
      - ./engine:/var/www
      - /var/www/node_modules
    restart: always
