version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    image: wabot_app
    container_name: wabot_app
    ports:
        - "3002:3002"
    volumes:
      - ./:/var/www
    restart: always
