version: '3'
networks:
  wabot_network:
    driver: bridge
services:

  engine:
    networks:
      - wabot_network
    build:
      context: ./
      dockerfile: docker/engine.dockerfile
    image: wabot_engine
    container_name: wabot_engine
    ports:
        - "3002"
    volumes:
      - ./engine:/var/www
      - /var/www/node_modules
    restart: always

  interface:
    networks:
      - wabot_network
    build:
      context: ./
      dockerfile: docker/interface.dockerfile
    image: wabot_interface
    container_name: wabot_interface
    volumes:
      - ./interface/web:/var/www
    restart: always

  web:
    networks:
      - wabot_network
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    image: wabot_web
    container_name: wabot_web
    restart: always
    volumes:
      - ./interface/web:/var/www
    ports:
      - "8080:80"
    depends_on:
      - interface

  queue:
    build:
      context: ./
      dockerfile: docker/queue.dockerfile
    image: wabot_queue
    networks:
      - wabot_network
    container_name: wabot_queue
    depends_on:
      - interface
    volumes:
      - ./interface/web:/var/www
    networks:
      - wabot_network
    restart: always

  redis:
    build:
      context: ./
      dockerfile: docker/redis.dockerfile
    container_name: wabot_redis
    image: wabot_redis
    networks:
      - wabot_network
    ports:
      - "6379:6379"
    restart: always